### ISSUE TITLE
How do I extract the core word from the actual word?

### ISSUE THREAD

**Issue by ithiru** [velsubra/Tamil#7]
Dear Vel,

I have been searching NLP for tamil for a while on Java/NodeJS as I am not very familiar in other languages. Found yours last year but couldn't make it run on my local and gave up.

Last week tried again and able to set it up successfully and ran few JUnits and found interesting. I know the lack of documentation is an issue, but given that this is Open Source, passion and doing free time, people can't ask for more.

I think your API is very specific to Tamil which I think is very good.

Anyways, I am working on small app to read tamil text, find the core word, feed to elastic search so it can find it when that word searched. For eg., if I have word அர்ச்சுனனால், then I want to extract அர்ச்சுனன், மகாபாரதத்தை => மகாபாரதம், கௌரவப்படையின் => கௌரவப்படை, etc.,

I tried your Punarchi APIs & REST API @ https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/index.html, still couldn't figure out :-)

Can you help me out?

TIA

**Comment by velsubra** [comment]
Hi Thiru
are you looking for Rest APIs ?
or Java APIs will do?

for Java APIs you would need to fire up the Dictionary first. I can point java APIs for it. It sounds like you want the base word from a compound word. you can play around with the existing APIs at

https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/apidocs/tamil/lang/TamilFactory.html

-Vel

**Comment by velsubra** [comment]
I just added a sample app with groovy code
Test here
https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/rest/apps/resources/base-wrod/bw.gv?compound=unnai

Here is the java API doc used

https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/apidocs/tamil/lang/TamilFactory.html

import tamil.lang._;
import tamil.lang.known._;
import tamil.lang.known.thodar._;
import tamil.lang.known.non.derived._;
import tamil.lang.api.parser.*;

String word =  R_QP_compound;
TamilWord tword =TamilFactory.getTransliterator(null).transliterate(word);
IKnownWord alreadyKnown = TamilFactory.getSystemDictionary().peek(tword);
if (alreadyKnown == null) {
    ParserResult result = TamilFactory.getCompoundWordParser().quickParse(tword);
    if (result == null || result.getSplitWords().isEmpty()) {
        throw new Exception("Unable to parse!" + tword.toString() +" : " +word);
    }
    alreadyKnown = result.getSplitWords().get(0);

}
 return recursive_FindRoot(alreadyKnown);

IKnownWord recursive_FindRoot(IKnownWord known) {

```
if (AbstractThodarMozhi.class.isAssignableFrom(known.getClass())) {
    List list = ((AbstractThodarMozhi)known).getWords();
    if (list.get(0).getWord().equals(known.getWord())) {
        return list.get(0);
    } else {
      return recursive_FindRoot(list.get(0));
    }
} else if (IBasePeyar.class.isAssignableFrom(known.getClass())) {
   return known.getPeyar();
} else if (IBaseVinai.class.isAssignableFrom(known.getclass())) {
   return known.getVinaiyadi();
} else {
    return known;
}
```

}

**Comment by velsubra** [comment]
https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/app-manager-edit-app.html#base-wrod
The security code  is bw, should you want to modify the app.

https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/rest/apps/resources/base-wrod/index.html

**Comment by velsubra** [comment]
https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/rest/apps/resources/base-wrod/bw.gv?compound=mahaabaarathaththudan
returns மகாபாரதம்

**Comment by velsubra** [comment]
https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/rest/apps/resources/base-wrod/bw.gv?compound=ntammai
returns நாம்

If the dictionary is down (sometimes it can go down... ), you may not get the required value.

https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/lookup.html show the dictionary status.

**Comment by ithiru** [comment]
Thanks for your detailed response, I am looking for Java API, will try your
suggestions and get back I need more details

Thanks again

**Comment by velsubra** [comment]
you can refert to  https://github.com/velsubra/Tamil/wiki/Dev-machine-setup for JDK 1.8 build
if you use java API, you would need to fire up the dictionary.

**Comment by ithiru** [comment]
Sorry, can you let me know How do I fire up the dictionary? I don't
remember seeing any கலை சொற்கள் file in the source.

**Comment by ithiru** [comment]
I tried the above and doesn't seem to work. May be the I am not "Firing the Dictionary"!. The JUnit is here - https://gist.github.com/ithiru/a7a7470072e476f2c604c797736b001c

**Comment by velsubra** [comment]
package test.simple;

import my.interest.lang.tamil.generated.types.TamilRootWords;
import my.interest.lang.tamil.impl.job.ExecuteManager;
import my.interest.lang.tamil.internal.api.PersistenceInterface;
import my.interest.lang.tamil.parser.impl.TamilPageListener;
import org.junit.Test;
import tamil.lang.TamilFactory;
import tamil.lang.TamilPage;
import tamil.lang.TamilWord;
import tamil.lang.api.parser.ParserResult;
import tamil.lang.known.IKnownWord;
import tamil.lang.known.non.derived.IBasePeyar;
import tamil.lang.known.non.derived.IBaseVinai;
import tamil.lang.known.thodar.AbstractThodarMozhi;

import java.io.ByteArrayInputStream;
import java.util.List;

/**
- Created by velsubra on 10/19/16.
  */
  public class DictionaryLoadTest {
  static {
      TamilFactory.init();
  }
  
  @Test
  public void testLoad() throws  Exception{
  
  ```
  PersistenceInterface inter = PersistenceInterface.get();
  inter.setAutoLoad(true);
  
  //Causes to read the persisted root verbs and sample applications
  //Since the auto load is true , words are generated and and added into the dictionary in the backgrond.
  TamilRootWords rootWords = inter.getAllRootWords();
  
  //Lets wait for some time for the dictionary to completely load
  int seconds = 0;
  while(!ExecuteManager.isQueueEmpty()) {
   Thread.currentThread().sleep(1000);
    System.out.println((++seconds) + " Seconds. Dictionary loading in the background with size now: " + TamilFactory.getSystemDictionary().size());
  }
  //The dictionary is hopefully loaded.
  
  
  // Now find the root words
  testPage();
  ```
  
  }
  
  private void testPage() {
      String s = "எதிர்பாராத்திருப்பங்கள்\n" + "=======================\n"
              + "எந்த எதிர்வினை மகாபாரதத்தை பெரிதும்  ஆவலுக்குள்ளாக்குகிறது.\n" + "\n"
              + "1. எந்தக்குலத்தைக்காக்க தன் வாழ்வை அற்பணித்தானோ அதேக்குலத்திற்பிறந்த அர்ச்சுனனால் அம்புக்கட்டிலில் உடல்முழுவதும் துழைக்கப்பட்டு   போர்க்களத்தில்    படுக்கவைக்கப்படுகிறான். - பீசுமன்\n"
              + "======\n" + "\n"
              + "2. எந்தநாட்டைவீழ்த்த வில்லாற்றலை அர்ச்சுனனுக்கு ஊட்டியூட்டி போதித்தானோ, அதே நாட்டின் மருமகனாகிவிட்ட   அர்ச்சுனனின்  அதே வில்லாற்றலால் போர்க்களத்தில்   எதிர்க்கப்படுகிறான் - துரோணன்.\n"
              + "=======\n" + "\n"
              + "3. எந்தவொருவனை போரில்வெல்லவேண்டி     தீராப்பகையும் போட்டியுங்கொண்டானோ அதேவொருவனாகிய அர்ச்சுனனின்   பாசத்திற்குரிய  மூத்தவண்ணனாகிப்போய் போர்க்களத்தில் கடேசித்தம்பியான    அர்ச்சுனனுக்கெதிராக    நின்றான் - கர்ணன்  (இதுவரை சகோதரப்பாசத்தை கண்டிறாத ஆனால் அதுபோன்றவோன்றிற்காக  ஏங்கியவன் கர்ணன்)\n"
              + "\n"
              + "இம்மூவர்தான் கௌரவப்படையின் முக்கியத்தளபதிகள்.   இம்மூவரின் ஆற்றலையும் (ஏதோவொரு வழியில்) உடைத்தவன் அர்ச்சுனன்.";
      // "=======================\n";
  
  ```
  // String s ="";
  TamilPage page = TamilPage.from(s);
  
  List<TamilWord> words = page.getAllTamilWords();
  System.out.println("# of words in the page:" + words.size());
  for (TamilWord tamilWord : words) {
      if (tamilWord.isPure() && !tamilWord.isEmpty()) {
          //TamilWord tword = TamilFactory.getTransliterator(null).transliterate(tamilWord.translitToEnglish());
          IKnownWord alreadyKnown = TamilFactory.getSystemDictionary().peek(tamilWord);
          if (alreadyKnown == null) {
              ParserResult result = TamilFactory.getCompoundWordParser().quickParse(tamilWord);
              if (result == null || result.getSplitWords().isEmpty()) {
                  System.out.println("The base word for:" + tamilWord.toString() +" could not be determined");
                  continue;
              } else {
                  alreadyKnown = result.getSplitWords().get(0);
              }
          }
  
          System.out.println(alreadyKnown.getWord().toString() +" -> " + recursive_FindRoot(alreadyKnown).getWord());
  
      }
  }
  // page.getAllTamilWords().stream().filter(word -> ((TamilWord)
  // word).isPure()).filter(word -> !((TamilWord)
  // word).isEmpty()).forEach(word ->
  // System.out.println(((TamilWord)word).translitToEnglish()));
  ```
  
  }
  
  IKnownWord recursive_FindRoot(IKnownWord known) {
  
  ```
  if (AbstractThodarMozhi.class.isAssignableFrom(known.getClass())) {
      List list = ((AbstractThodarMozhi) known).getWords();
      if (((IKnownWord) list.get(0)).getWord().equals(known.getWord())) {
          return (IKnownWord) list.get(0);
      } else {
          return recursive_FindRoot((IKnownWord) list.get(0));
      }
  } else if (IBasePeyar.class.isAssignableFrom(known.getClass())) {
      return  ((IBasePeyar)known).getPeyar();
  } else if (IBaseVinai.class.isAssignableFrom(known.getClass())) {
      return ((IBaseVinai)known).getVinaiyadi();
  } else {
      return known;
  }
  ```
  
  }
  }

Something like this should work. Can you try?

Please note, the dictionary should be fully up, before doing any parsing related work

**Comment by ithiru** [comment]
Thanks, will check it out.

**Comment by ithiru** [comment]
Worked fine after commenting out this line FileBasedPersistence.populateSorted

//reCompileAllScripts();

otherwise I get this error 

java.lang.NoClassDefFoundError: org/apache/maven/model/io/xpp3/MavenXpp3Reader
    at my.interest.lang.tamil.impl.ApplicationClassloader.addPom(ApplicationClassloader.java:70)
    at my.interest.lang.tamil.impl.ApplicationClassloader.addPom(ApplicationClassloader.java:53)
    at my.interest.lang.tamil.impl.ApplicationClassloader.addPom(ApplicationClassloader.java:45)
    at my.interest.lang.tamil.impl.ApplicationClassloader.addPom(ApplicationClassloader.java:41)
    at my.interest.lang.tamil.xml.AppCache.buildClassloader(AppCache.java:47)
    at my.interest.lang.tamil.impl.FileBasedPersistence.reCompileAllScripts(FileBasedPersistence.java:158)
    at my.interest.lang.tamil.impl.FileBasedPersistence.populateSorted(FileBasedPersistence.java:146)
    at my.interest.lang.tamil.impl.FileBasedPersistence.getAllRootWords(FileBasedPersistence.java:249)
    at in.thiru.jemo.DictionaryLoadTest.testLoad(DictionaryLoadTest.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.model.io.xpp3.MavenXpp3Reader
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 32 more

**Comment by ithiru** [comment]
For new words which is not in dictionary - How do I add it? I saw this link - https://javas2-jcscdc.java.us2.oraclecloudapps.com/tamil/noun-filter.html where I can copy paste and it shows new words.

Please confirm.
